# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8651c1e0f5b7e18a2e23240bd1762f6c0fc3fea025839d6b4c3e5ced9082c95275cd1e05f800a31eb2e90cf2f6b18e551a87fc87bb5ad13f4bee535af547deb

test:
  secret_key_base: 622177a3000054deae64f25b60e9ba04401d261f493fb004b0b249ee2d1094ce4d853280cf2f0e91544b37f2f6ae09b5bff65898ef27f9b1137fa24e72fe740c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
